# Generated by Django 3.0.1 on 2020-02-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('viewer_count', models.IntegerField(blank=True, null=True)),
                ('game', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_live', models.BooleanField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta_time', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube'), ('Mixer', 'Mixer')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Viewership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.LiveSession')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Streamer'),
        ),
    ]
