# Generated by Django 3.0.1 on 2019-12-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[(4, 'Facebook'), (2, 'Youtube'), (1, 'Twitch'), (3, 'Mixer')], max_length=30)),
                ('subscriber_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_viewers', models.IntegerField()),
                ('avg_viewers', models.IntegerField()),
                ('is_live', models.BooleanField()),
                ('current_viewers', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.Streamer')),
            ],
        ),
    ]
