# Generated by Django 3.0.1 on 2020-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Twitch', 'Twitch'), ('Mixer', 'Mixer'), ('Facebook', 'Facebook')], max_length=30),
        ),
    ]
