# Generated by Django 3.0.1 on 2019-12-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='rank',
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Mixer', 'Mixer'), ('Youtube', 'Youtube'), ('Twitch', 'Twitch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
