# Generated by Django 3.0.1 on 2020-02-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20200210_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Mixer', 'Mixer'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
