# Generated by Django 3.0.1 on 2019-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20191220_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Mixer', 'Mixer'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
