# Generated by Django 3.0.1 on 2020-02-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20200209_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
