# Generated by Django 3.0.1 on 2019-12-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_auto_20191220_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='avg_viewers',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='max_viewers',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='subscriber_count',
        ),
        migrations.AlterField(
            model_name='livesession',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Twitch', 'Twitch'), ('Mixer', 'Mixer'), ('Facebook', 'Facebook'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
