# Generated by Django 3.0.1 on 2020-02-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_auto_20200209_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='delta_time',
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Mixer', 'Mixer'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
