# Generated by Django 3.0.1 on 2019-12-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_auto_20191226_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='current_viewers',
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube')], max_length=30),
        ),
        migrations.CreateModel(
            name='Viewership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('live_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.LiveSession')),
            ],
        ),
    ]
