# Generated by Django 3.0.1 on 2019-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20191226_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Mixer', 'Mixer'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
