# Generated by Django 3.0.1 on 2020-02-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_auto_20200209_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='delta_time',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=30),
        ),
    ]
