# Generated by Django 3.0.1 on 2020-02-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_auto_20200209_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Mixer', 'Mixer'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
