# Generated by Django 3.0.1 on 2019-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_auto_20191226_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Twitch', 'Twitch'), ('Mixer', 'Mixer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='viewership',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
