# Generated by Django 3.0.1 on 2019-12-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20191226_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewership',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Mixer', 'Mixer'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
