# Generated by Django 3.0.1 on 2019-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_auto_20191227_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='viewer_count',
            field=models.IntegerField(default=0),
        ),
    ]
