# Generated by Django 3.0.1 on 2019-12-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_auto_20191228_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='viewer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Mixer', 'Mixer'), ('Youtube', 'Youtube'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
