# Generated by Django 3.0.1 on 2020-01-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0010_auto_20200104_0125'),
        ('rankings', '0012_auto_20191228_1744'),
    ]

    operations = [
    ]
