# Generated by Django 3.0.1 on 2020-01-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0013_merge_20200109_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
