# Generated by Django 3.0.1 on 2020-01-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_auto_20200109_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='game',
            field=models.CharField(default='League of Legends', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook'), ('Twitch', 'Twitch')], max_length=30),
        ),
    ]
