# Generated by Django 3.0.1 on 2020-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_auto_20200116_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube'), ('Facebook', 'Facebook')], max_length=30),
        ),
    ]
