# Generated by Django 3.0.1 on 2020-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0018_auto_20200118_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube'), ('Mixer', 'Mixer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
