# Generated by Django 3.0.1 on 2020-02-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0020_auto_20200207_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='language',
            field=models.CharField(default='EN', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livesession',
            name='is_live',
            field=models.BooleanField(default='EN'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='platform',
            field=models.CharField(choices=[('Mixer', 'Mixer'), ('Facebook', 'Facebook'), ('Twitch', 'Twitch'), ('Youtube', 'Youtube')], max_length=30),
        ),
    ]
